"""
Amazon Bedrock AgentCore Runtime entry point for the compliance-ops-bedrock chatbot.

This module wraps the existing Strands agent with the BedrockAgentCoreApp
framework so the agent can be deployed to the AgentCore managed runtime
(container-based, AWS-managed scaling) instead of – or alongside – the
Lambda Function URL deployment.

The entrypoint function receives a payload dict from AgentCore, calls the
Strands agent, and returns a JSON-serialisable dict that AgentCore forwards
to the caller.

EU AI Act Art. 50(1): the ai_disclosure field in every response satisfies
the obligation to inform users they are interacting with an AI system.

Running locally:
    python -m app.agentcore_app
    # Starts Uvicorn on port 8080; test with:
    # curl -X POST http://localhost:8080/invocations \
    #      -H "Content-Type: application/json" \
    #      -d '{"prompt": "What GDPR controls are implemented?"}'
"""
import logging
import uuid
from typing import Any

from bedrock_agentcore import BedrockAgentCoreApp

# Re-use the agent singleton initialised once at module load.
# Import order matters: agent.py reads env vars at import time.
from app.agent import agent

logger = logging.getLogger(__name__)
logger.setLevel(logging.INFO)

app = BedrockAgentCoreApp()


@app.entrypoint
def invoke(payload: dict[str, Any]) -> dict[str, Any]:
    """Process a compliance chatbot request via AgentCore Runtime.

    AgentCore sends a JSON payload to POST /invocations.  The expected
    request shape mirrors the existing Lambda chatbot route:

        {"prompt": "<user message>", "session_id": "<optional uuid>"}

    The key "prompt" is the AgentCore SDK convention; "message" is also
    accepted as a fallback for backwards compatibility with the Lambda route.

    Args:
        payload: Decoded JSON body from the AgentCore /invocations request.

    Returns:
        JSON-serialisable dict::

            {
                "response": "<agent reply>",
                "session_id": "<uuid>",
                "ai_disclosure": "<Art. 50(1) notice>"
            }
    """
    # Accept both "prompt" (AgentCore convention) and "message" (Lambda convention).
    message: str = (
        payload.get("prompt") or payload.get("message") or ""
    ).strip()

    if not message:
        logger.warning("invoke() called with empty prompt/message")
        return {
            "error": "'prompt' (or 'message') field is required and must not be empty.",
            "session_id": None,
            "ai_disclosure": (
                "This response was generated by an AI system "
                "(ComplianceOps Reference Architecture demo). "
                "It is not legal advice and must be reviewed by qualified humans."
            ),
        }

    session_id: str = payload.get("session_id") or str(uuid.uuid4())
    logger.info("session=%s message_length=%d", session_id, len(message))

    try:
        result = agent(message)
        # Strands AgentResult: str() yields the final text response.
        response_text: str = str(result)
    except Exception as exc:
        logger.exception("Agent invocation failed for session=%s: %s", session_id, exc)
        return {
            "error": f"Agent error: {exc}",
            "session_id": session_id,
            "ai_disclosure": (
                "This response was generated by an AI system "
                "(ComplianceOps Reference Architecture demo). "
                "It is not legal advice and must be reviewed by qualified humans."
            ),
        }

    logger.info("session=%s response_length=%d", session_id, len(response_text))

    return {
        "response": response_text,
        "session_id": session_id,
        # EU AI Act Art. 50(1) disclosure in every response body.
        "ai_disclosure": (
            "This response was generated by an AI system "
            "(ComplianceOps Reference Architecture demo). "
            "It is not legal advice and must be reviewed by qualified humans."
        ),
    }


if __name__ == "__main__":
    app.run()
