"""
AWS Lambda handler for the compliance-ops-bedrock chatbot endpoint.

Accepts POST requests with body: {"message": "<user input>", "session_id": "<uuid>"}
Returns: {"response": "<agent reply>", "session_id": "<uuid>"}

Session persistence: conversation history is managed in-process by the Strands
agent (it maintains a message list per agent instance). For multi-Lambda-instance
scaling, session history would need to be externalised to DynamoDB; this is
acceptable for the demo which runs at low concurrency.

EU AI Act Art. 50(1): the system prompt and every response header includes a
disclosure that responses are AI-generated. The "x-ai-generated" response header
makes this machine-readable for downstream integrations.
"""
import json
import logging
import os
import uuid
from typing import Any

logger = logging.getLogger(__name__)
logger.setLevel(logging.INFO)

# Import the agent singleton. The import-time initialisation runs once per
# cold start; subsequent invocations reuse the already-initialised agent.
from app.agent import agent

_CORS_ORIGIN = os.environ.get("CORS_ORIGIN", "*")

_RESPONSE_HEADERS = {
    "Content-Type": "application/json",
    "Access-Control-Allow-Origin": _CORS_ORIGIN,
    # EU AI Act Art. 50 machine-readable disclosure
    "X-AI-Generated": "true",
    "X-AI-System": "compliance-ops-bedrock-demo",
}


def _ok(body: dict[str, Any]) -> dict[str, Any]:
    return {
        "statusCode": 200,
        "headers": _RESPONSE_HEADERS,
        "body": json.dumps(body),
    }


def _err(status: int, message: str) -> dict[str, Any]:
    return {
        "statusCode": status,
        "headers": _RESPONSE_HEADERS,
        "body": json.dumps({"error": message}),
    }


def handler(event: dict[str, Any], context: Any) -> dict[str, Any]:
    """Lambda entry point.

    Expected event shape (Lambda Function URL or API Gateway proxy):
        {
          "body": "{\"message\": \"...\", \"session_id\": \"...\"}",
          "httpMethod": "POST"   // or requestContext.http.method for Function URL
        }

    The session_id is optional; a new UUID is generated if omitted.
    """
    # Handle CORS pre-flight
    method = (
        event.get("httpMethod")
        or event.get("requestContext", {}).get("http", {}).get("method", "")
    ).upper()
    if method == "OPTIONS":
        return {"statusCode": 204, "headers": _RESPONSE_HEADERS, "body": ""}

    if method not in ("POST", ""):
        return _err(405, "Method not allowed. Use POST.")

    # Parse request body
    raw_body = event.get("body") or "{}"
    try:
        body = json.loads(raw_body)
    except json.JSONDecodeError:
        return _err(400, "Request body must be valid JSON.")

    message: str = body.get("message", "").strip()
    if not message:
        return _err(400, "'message' field is required and must not be empty.")

    session_id: str = body.get("session_id") or str(uuid.uuid4())

    logger.info("session=%s message_length=%d", session_id, len(message))

    # Invoke the Strands agent
    try:
        result = agent(message)
        # Strands returns an AgentResult; str() gives the final text response.
        response_text = str(result)
    except Exception as exc:
        logger.exception("Agent invocation failed for session=%s: %s", session_id, exc)
        return _err(500, f"Agent error: {exc}")

    logger.info("session=%s response_length=%d", session_id, len(response_text))

    return _ok(
        {
            "response": response_text,
            "session_id": session_id,
            # EU AI Act Art. 50 disclosure in response body as well
            "ai_disclosure": (
                "This response was generated by an AI system "
                "(ComplianceOps Reference Architecture demo). "
                "It is not legal advice and must be reviewed by qualified humans."
            ),
        }
    )
